source "https://rubygems.org"

gem "jekyll", "~> 3.10"
gem "jekyll-text-theme", "~> 2.2"
gem "jekyll-remote-theme"
gem "jekyll-feed"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jemoji"
gem "kramdown-parser-gfm"
